version: "3"

services:
  app:
    image: golang:1.10-stretch
    volumes:
      - .:/go/src/github.com/pdrosos/hyperledger-fabric-demo/seller
    working_dir: /go/src/github.com/pdrosos/hyperledger-fabric-demo/seller
    ports:
      - 7777:7777
    entrypoint: ./bin/apiserver --port 7777
