version: '2'

volumes:
  orderer.blockchain.localhost:
  peer0.seller.blockchain.localhost:
  peer1.seller.blockchain.localhost:
  peer0.courier.blockchain.localhost:
  peer1.courier.blockchain.localhost:

networks:
  basic:

services:

  ca.seller.blockchain.localhost:
    image: hyperledger/fabric-ca
    container_name: ca.seller.blockchain.localhost
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.seller.blockchain.localhost
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller.blockchain.localhost-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4abad60cf2c3bb5c5f0ef1b409d77f34140acae984afa7eb06de71ce2b7f1843_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.seller.blockchain.localhost-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4abad60cf2c3bb5c5f0ef1b409d77f34140acae984afa7eb06de71ce2b7f1843_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/seller.blockchain.localhost/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - basic

  ca.courier.blockchain.localhost:
      image: hyperledger/fabric-ca
      container_name: ca.courier.blockchain.localhost
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.courier.blockchain.localhost
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.courier.blockchain.localhost-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/170646d10f02f88ba641ffd65aa6200edd1f3a8f0c4ab2c5a9e3dc80bfca5f6f_sk
      ports:
        - 8054:7054
      command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.courier.blockchain.localhost-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/170646d10f02f88ba641ffd65aa6200edd1f3a8f0c4ab2c5a9e3dc80bfca5f6f_sk -b admin:adminpw -d'
      volumes:
        - ./crypto-config/peerOrganizations/courier.blockchain.localhost/ca/:/etc/hyperledger/fabric-ca-server-config
      networks:
        - basic

  orderer.blockchain.localhost:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.blockchain.localhost
    container_name: orderer.blockchain.localhost
    networks:
      - basic

  peer0.seller.blockchain.localhost:
    container_name: peer0.seller.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.seller.blockchain.localhost
    networks:
      - basic

  peer1.seller.blockchain.localhost:
    container_name: peer1.seller.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.seller.blockchain.localhost
    networks:
      - basic

  peer0.courier.blockchain.localhost:
    container_name: peer0.courier.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.courier.blockchain.localhost
    networks:
      - basic

  peer1.courier.blockchain.localhost:
    container_name: peer1.courier.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.courier.blockchain.localhost
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.seller.blockchain.localhost:7051
      - CORE_PEER_LOCALMSPID=SellerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.blockchain.localhost/peers/peer0.seller.blockchain.localhost/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.blockchain.localhost/peers/peer0.seller.blockchain.localhost/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.blockchain.localhost/peers/peer0.seller.blockchain.localhost/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.blockchain.localhost/users/Admin@seller.blockchain.localhost/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.blockchain.localhost
      - peer0.seller.blockchain.localhost
      - peer1.seller.blockchain.localhost
      - peer0.courier.blockchain.localhost
      - peer1.courier.blockchain.localhost
    networks:
      - basic
