version: '2'

volumes:
  orderer.blockchain.localhost:
  peer0.seller.blockchain.localhost:
  peer1.seller.blockchain.localhost:
  peer0.courier.blockchain.localhost:
  peer1.courier.blockchain.localhost:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-seller
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller.blockchain.localhost-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0b52106532395360f29820a0a1437ca7b06db40cdc31e1cf553222ab407a13e8_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.seller.blockchain.localhost-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0b52106532395360f29820a0a1437ca7b06db40cdc31e1cf553222ab407a13e8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/seller.blockchain.localhost/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSeller
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-courier
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.courier.blockchain.localhost-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/04f202d0e7e7a524d80ef84548c1fc264bc6144023324e401f4b0fc92b238d88_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.courier.blockchain.localhost-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/04f202d0e7e7a524d80ef84548c1fc264bc6144023324e401f4b0fc92b238d88_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/courier.blockchain.localhost/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCourier
    networks:
      - byfn

  orderer.blockchain.localhost:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.blockchain.localhost
    container_name: orderer.blockchain.localhost
    networks:
      - byfn

  peer0.seller.blockchain.localhost:
    container_name: peer0.seller.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.seller.blockchain.localhost
    networks:
      - byfn

  peer1.seller.blockchain.localhost:
    container_name: peer1.seller.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.seller.blockchain.localhost
    networks:
      - byfn

  peer0.courier.blockchain.localhost:
    container_name: peer0.courier.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.courier.blockchain.localhost
    networks:
      - byfn

  peer1.courier.blockchain.localhost:
    container_name: peer1.courier.blockchain.localhost
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.courier.blockchain.localhost
    networks:
      - byfn
