version: '2'

services:

  orderer.blockchain.localhost:
    container_name: orderer.blockchain.localhost
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/blockchain.localhost/orderers/orderer.blockchain.localhost/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/blockchain.localhost/orderers/orderer.blockchain.localhost/tls/:/var/hyperledger/orderer/tls
    - orderer.blockchain.localhost:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.seller.blockchain.localhost:
    container_name: peer0.seller.blockchain.localhost
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.seller.blockchain.localhost
      - CORE_PEER_ADDRESS=peer0.seller.blockchain.localhost:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller.blockchain.localhost:7051
      - CORE_PEER_LOCALMSPID=SellerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/seller.blockchain.localhost/peers/peer0.seller.blockchain.localhost/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/seller.blockchain.localhost/peers/peer0.seller.blockchain.localhost/tls:/etc/hyperledger/fabric/tls
        - peer0.seller.blockchain.localhost:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.seller.blockchain.localhost:
    container_name: peer1.seller.blockchain.localhost
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.seller.blockchain.localhost
      - CORE_PEER_ADDRESS=peer1.seller.blockchain.localhost:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.seller.blockchain.localhost:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller.blockchain.localhost:7051
      - CORE_PEER_LOCALMSPID=SellerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/seller.blockchain.localhost/peers/peer1.seller.blockchain.localhost/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/seller.blockchain.localhost/peers/peer1.seller.blockchain.localhost/tls:/etc/hyperledger/fabric/tls
        - peer1.seller.blockchain.localhost:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.courier.blockchain.localhost:
    container_name: peer0.courier.blockchain.localhost
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.courier.blockchain.localhost
      - CORE_PEER_ADDRESS=peer0.courier.blockchain.localhost:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.courier.blockchain.localhost:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.courier.blockchain.localhost:7051
      - CORE_PEER_LOCALMSPID=CourierMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/courier.blockchain.localhost/peers/peer0.courier.blockchain.localhost/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/courier.blockchain.localhost/peers/peer0.courier.blockchain.localhost/tls:/etc/hyperledger/fabric/tls
        - peer0.courier.blockchain.localhost:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.courier.blockchain.localhost:
    container_name: peer1.courier.blockchain.localhost
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.courier.blockchain.localhost
      - CORE_PEER_ADDRESS=peer1.courier.blockchain.localhost:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.courier.blockchain.localhost:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.courier.blockchain.localhost:7051
      - CORE_PEER_LOCALMSPID=CourierMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/courier.blockchain.localhost/peers/peer1.courier.blockchain.localhost/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/courier.blockchain.localhost/peers/peer1.courier.blockchain.localhost/tls:/etc/hyperledger/fabric/tls
        - peer1.courier.blockchain.localhost:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
