#
# Copyright Altoros. All Rights Reserved.
#

version: '2'

services:

  ca.seller.blockchain.localhost:
    container_name: ca.seller.blockchain.localhost
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller.blockchain.localhost-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ab1ccfdd6cba7680a7518a4f188e4db18be1204c66971b62d92ac786947db52e_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller.blockchain.localhost-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ab1ccfdd6cba7680a7518a4f188e4db18be1204c66971b62d92ac786947db52e_sk
#    ports:
#      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/seller.blockchain.localhost/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../artifacts/fabric-ca-server-config-seller.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml

  peer0.seller.blockchain.localhost:
    container_name: peer0.seller.blockchain.localhost
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.seller.blockchain.localhost
      - CORE_PEER_LOCALMSPID=sellerMSP
      - CORE_PEER_ADDRESS=peer0.seller.blockchain.localhost:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/seller.blockchain.localhost/peers/peer0.seller.blockchain.localhost/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.seller.blockchain.localhost
    

  peer1.seller.blockchain.localhost:
    container_name: peer1.seller.blockchain.localhost
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.seller.blockchain.localhost
      - CORE_PEER_LOCALMSPID=sellerMSP
      - CORE_PEER_ADDRESS=peer1.seller.blockchain.localhost:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/seller.blockchain.localhost/peers/peer1.seller.blockchain.localhost/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.seller.blockchain.localhost
    

  # fabric-rest api server
  api.seller.blockchain.localhost:
    extends:
      file: base.yaml
      service: api-base
    container_name: api.seller.blockchain.localhost
    ports:
      - 4000:4000
    environment:
      - ORG=seller
      - PORT=4000
    volumes:
      - ../artifacts/api/seller/hosts:/etc/hosts
    depends_on:
      - peer0.seller.blockchain.localhost
      - peer1.seller.blockchain.localhost
    

  cli.blockchain.localhost:
    container_name: cli.blockchain.localhost
    extends:
      file: base.yaml
      service: cli-base
    volumes:
      - ../artifacts/crypto-config/ordererOrganizations/blockchain.localhost/orderers/orderer.blockchain.localhost/tls:/etc/hyperledger/crypto/orderer/tls

  cli.seller.blockchain.localhost:
    container_name: cli.seller.blockchain.localhost
    extends:
      service: cli.blockchain.localhost
    environment:
      - CORE_PEER_LOCALMSPID=sellerMSP
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/seller.blockchain.localhost/users/Admin@seller.blockchain.localhost:/etc/hyperledger/crypto/peer
    

  # simple http server to disseminate certificates
  www.seller.blockchain.localhost:
    extends:
      file: base.yaml
      service: www-base
    container_name: www.seller.blockchain.localhost
    ports:
      - 8081:80
